In [1]:
#laplace_coefficient.ipynb
#by Joe Hahn, jmh.datasciences@gmail.com, 20 January 2024.
#compute laplace coefficients for m=2 inner Lindblad resonance

In [2]:
#integrand of laplace coefficient
import numpy as np
def integrand(t, m, s, beta):
    num = (2/np.pi)*np.cos(m*t)
    den = (1 + beta**2 - 2*beta*np.cos(t))**s
    intgrnd = num/den
    return intgrnd

In [3]:
#laplace coefficient
from scipy.integrate import quad
def lc(beta, m, s):
    lc = quad(integrand, 0, np.pi, args=(m,s,beta))
    return lc[0]

In [4]:
#derivative of lc wrt beta
from scipy.misc import derivative
def dlc(beta, m, s):
    return derivative(lc, beta, dx=1e-8, args=(m,s))

In [5]:
#compute laplace coefficient
m = 2.0
s = 0.5
beta = 0.6335710236913903
lc(beta, m, s)

0.3706184400476837

In [6]:
#compute derivate wrt beta
dlc(beta, m, s)

1.4782643609212442

In [7]:
#use confirm via finite differences
db = 0.001
dlc_est = lc(beta + db, m, s) - lc(beta - db, m, s)
dlc_est /= 2*db
dlc_est

1.4782684814403924

In [8]:
#use np.vectorize to compute laplace coefficient across numpy array
betas = [[beta, beta + 0.1, beta + 0.2], [beta, beta + 0.1, beta + 0.2]]
beta_arr = np.array(betas)
print 'beta_arr = ', beta_arr
print 'beta_arr.shape = ', beta_arr.shape
lc_vectorized = np.vectorize(lc)
lc_arr =  lc_vectorized(beta_arr, m, s)
print 'lc_arr.shape = ', lc_arr.shape
lc_arr

beta_arr =  [[0.63357102 0.73357102 0.83357102]
 [0.63357102 0.73357102 0.83357102]]
beta_arr.shape =  (2, 3)
lc_arr.shape =  (2, 3)


array([[0.37061844, 0.54923135, 0.8265513 ],
       [0.37061844, 0.54923135, 0.8265513 ]])

In [9]:
dlc_vectorized = np.vectorize(dlc)
dlc_arr =  dlc_vectorized(beta_arr, m, s)
dlc_arr

array([[1.47826436, 2.16063624, 3.60322984],
       [1.47826436, 2.16063624, 3.60322984]])